export enum RoleName {
  SUPER_ADMIN_ROLE = 'SUPER_ADMIN_ROLE',
  ADMIN_ROLE = 'ADMIN_ROLE',
  CUSTOMER_ROLE = 'CUSTOMER_ROLE',
  EMPLOYEE_ROLE = 'EMPLOYEE_ROLE',
  MERCHANT_ROLE = 'MERCHANT_ROLE',
  SUPPLIER_ROLE = 'SUPPLIER_ROLE',
  USER_ROLE = 'USER_ROLE',
  AFFILIATOR_ROLE = 'AFFILIATOR_ROLE',
}
